/**
 * Deterministic data for UI/E2E automation (`npm run seed:e2e`).
 *
 * Run it against the isolated E2E environment (`npm run e2e:env:up`, gateway on :3100) right after
 * it starts from empty volumes. Gateway-only like the other seeds. Names, prices and scenarios are
 * fixed, so flows can assert exact text and totals. Database ids are generated by the services, so
 * the ids flows need are written to a manifest (E2E_MANIFEST, default ./e2e-seed-manifest.json).
 *
 * Safe to rerun: accounts, catalog and each order scenario are reused when they already exist.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import {
  del,
  dispatch,
  driveDelivery,
  ensureDriverProfile,
  get,
  log,
  loginOrRegister,
  patch,
  placeOrder,
  runSeed,
  seedRestaurant,
  sleep,
  useGateway,
  type Auth,
  type MenuItem,
  type Order,
  type RestaurantSeed,
} from './lib/gateway-seed';

const API_URL = process.env.API_URL || 'http://localhost:3100';
/** Test-only credential for the throw-away E2E environment; never used by any other environment. */
const PASSWORD = process.env.E2E_PASSWORD || 'Qa-Only-Passw0rd!';
const MANIFEST = resolve(process.env.E2E_MANIFEST || 'e2e-seed-manifest.json');

export const QA = {
  customer: {
    email: 'qa.customer@delivery-plus.test',
    fullName: 'QA Customer',
    phone: '+1 555 000 0001',
    address: '1 Test Street, Apt 1',
  },
  otherCustomer: {
    email: 'qa.customer2@delivery-plus.test',
    fullName: 'QA Other Customer',
    address: '2 Test Street, Apt 2',
  },
  restaurant: { email: 'qa.restaurant@delivery-plus.test', fullName: 'QA Restaurant Owner' },
  driver: { email: 'qa.driver@delivery-plus.test', fullName: 'QA Driver', plate: 'QA-0001' },
} as const;

const RESTAURANTS: RestaurantSeed[] = [
  {
    name: 'QA Kitchen',
    description: 'Deterministic restaurant for UI tests',
    address: '100 QA Avenue',
    status: 'OPEN',
    categories: [
      {
        name: 'Mains',
        items: [
          { name: 'QA Burger', description: 'Always $10.00', price: 10 },
          { name: 'QA Pasta', description: 'Always $12.50', price: 12.5 },
        ],
      },
      {
        name: 'Sides',
        items: [
          { name: 'QA Fries', description: 'Always $4.00', price: 4 },
          { name: 'QA Soup', description: 'Always sold out', price: 5, available: false },
        ],
      },
      { name: 'Drinks', items: [{ name: 'QA Lemonade', description: 'Always $3.00', price: 3 }] },
    ],
  },
  {
    name: 'QA Night Cafe',
    description: 'Closed restaurant for filter tests',
    address: '200 QA Avenue',
    status: 'CLOSED',
    categories: [
      { name: 'Mains', items: [{ name: 'QA Night Toast', description: 'Always $6.00', price: 6 }] },
    ],
  },
];

function assertSafeTarget() {
  const host = new URL(API_URL).hostname;
  if (!['localhost', '127.0.0.1'].includes(host) && process.env.E2E_ALLOW_REMOTE !== '1') {
    throw new Error(
      `Refusing to seed E2E accounts into ${API_URL}. Set E2E_ALLOW_REMOTE=1 for a dedicated remote test env.`,
    );
  }
}

async function findOrder(customer: Auth, status: string): Promise<Order | undefined> {
  const { items } = await get<{ items: Order[] }>('/api/orders?limit=100', customer);
  return items.find((order) => order.status === status);
}

async function waitForNotifications(customer: Auth, atLeast: number) {
  const deadline = Date.now() + 20_000;
  let total = 0;
  while (Date.now() < deadline) {
    total = (await get<{ total: number }>('/api/notifications?limit=1', customer)).total;
    if (total >= atLeast) return total;
    await sleep(1_000);
  }
  throw new Error(`Expected at least ${atLeast} notifications for the QA customer, found ${total}`);
}

async function seedE2e() {
  assertSafeTarget();
  useGateway(API_URL);
  log(`Seeding deterministic E2E data through ${API_URL}\n`);

  log('Accounts');
  const owner = await loginOrRegister(
    QA.restaurant.email,
    PASSWORD,
    QA.restaurant.fullName,
    'RESTAURANT_OWNER',
  );
  const driver = await loginOrRegister(QA.driver.email, PASSWORD, QA.driver.fullName, 'DRIVER');
  const customer = await loginOrRegister(
    QA.customer.email,
    PASSWORD,
    QA.customer.fullName,
    'CUSTOMER',
    QA.customer.phone,
  );
  const otherCustomer = await loginOrRegister(
    QA.otherCustomer.email,
    PASSWORD,
    QA.otherCustomer.fullName,
    'CUSTOMER',
  );

  await patch(
    '/api/users/me',
    { fullName: QA.customer.fullName, phone: QA.customer.phone, address: QA.customer.address },
    customer,
  );
  // Checkout needs a drop-off address; the S4 order is placed as this customer.
  await patch('/api/users/me', { address: QA.otherCustomer.address }, otherCustomer);
  await ensureDriverProfile(driver, 'Bicycle', QA.driver.plate);
  const driverProfile = await get<{ id: string }>('/api/drivers/me', driver);

  log('\nRestaurants');
  const items = new Map<string, MenuItem>();
  const restaurantIds: Record<string, string> = {};
  for (const seed of RESTAURANTS) {
    const { restaurant, items: seeded } = await seedRestaurant(seed, owner);
    restaurantIds[seed.name] = restaurant.id;
    seeded.forEach((item, name) => items.set(name, item));
  }
  const item = (name: string) => items.get(name)!;

  log('\nOrder scenarios');
  // S1 delivered: produces an "Order Confirmed" notification and a completed delivery.
  let delivered = await findOrder(customer, 'DELIVERED');
  if (!delivered) {
    log('• S1 delivered (1× QA Burger)');
    delivered = await placeOrder(customer, [{ item: item('QA Burger'), quantity: 1 }], 'success');
    const deliveryId = await dispatch(delivered.id, owner, driver, driverProfile.id);
    await driveDelivery(deliveryId, driver, true);
  }

  // S2 declined payment.
  let failed = await findOrder(customer, 'FAILED');
  if (!failed) {
    log('• S2 failed payment (1× QA Fries)');
    failed = await placeOrder(customer, [{ item: item('QA Fries'), quantity: 1 }], 'failure');
  }

  // S3 ready for pickup, no delivery yet: the "Finding a driver" state on order detail.
  let awaiting = await findOrder(customer, 'READY_FOR_PICKUP');
  if (!awaiting) {
    log('• S3 ready for pickup, no delivery (1× QA Pasta)');
    awaiting = await placeOrder(customer, [{ item: item('QA Pasta'), quantity: 1 }], 'success');
    await patch(`/api/orders/${awaiting.id}/status`, { status: 'PREPARING' }, owner);
    await patch(`/api/orders/${awaiting.id}/status`, { status: 'READY_FOR_PICKUP' }, owner);
  }

  // S4 another customer's order: the QA customer must not be able to open it.
  let foreign = await findOrder(otherCustomer, 'CONFIRMED');
  if (!foreign) {
    log('• S4 other customer, confirmed (1× QA Lemonade)');
    foreign = await placeOrder(
      otherCustomer,
      [{ item: item('QA Lemonade'), quantity: 1 }],
      'success',
    );
  }

  await del('/api/cart', customer);
  const notifications = await waitForNotifications(customer, 2);
  const { status: driverStatus } = await get<{ status: string }>('/api/drivers/me', driver);

  const manifest = {
    apiUrl: API_URL,
    password: PASSWORD,
    accounts: QA,
    restaurants: restaurantIds,
    menuItems: Object.fromEntries([...items].map(([name, value]) => [name, value.id])),
    driverId: driverProfile.id,
    orders: {
      delivered: delivered.id,
      failed: failed.id,
      awaitingDriver: awaiting.id,
      otherCustomer: foreign.id,
    },
  };
  writeFileSync(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`);

  log(`
E2E data ready (${notifications} notifications, QA driver ${driverStatus}, empty cart).
  Manifest: ${MANIFEST}
  Customer: ${QA.customer.email}   Restaurant: ${QA.restaurant.email}   Driver: ${QA.driver.email}`);
}

runSeed('E2E seed', seedE2e);
